package com.xiaya.ucenter.mapper;

import com.xiaya.ucenter.model.UserCenter;
import com.xiaya.ucenter.model.UserCenterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCenterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int countByExample(UserCenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int deleteByExample(UserCenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int insert(UserCenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int insertSelective(UserCenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    List<UserCenter> selectByExample(UserCenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    UserCenter selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserCenter record, @Param("example") UserCenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int updateByExample(@Param("record") UserCenter record, @Param("example") UserCenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int updateByPrimaryKeySelective(UserCenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_center
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    int updateByPrimaryKey(UserCenter record);
}