package com.xiaya.ucenter.mapper;

import com.xiaya.ucenter.model.UserBistats;
import com.xiaya.ucenter.model.UserBistatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBistatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int countByExample(UserBistatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int deleteByExample(UserBistatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int insert(UserBistats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int insertSelective(UserBistats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    List<UserBistats> selectByExample(UserBistatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    UserBistats selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserBistats record, @Param("example") UserBistatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int updateByExample(@Param("record") UserBistats record, @Param("example") UserBistatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int updateByPrimaryKeySelective(UserBistats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_bistats
     *
     * @mbggenerated Wed Feb 03 15:41:23 CST 2016
     */
    int updateByPrimaryKey(UserBistats record);
}