package com.xiaya.ucenter.model;

import java.util.Date;

public class UserCenter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.user_id
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.mobile
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.is_mobile_bind
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer isMobileBind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.user_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.password
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.email
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.birthday
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.signature
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.gender
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Long score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.city
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.nick_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.avatar
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.active_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String activeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.activation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String activation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.create_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.update_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.find_pw_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String findPwCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.user_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.security_level
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer securityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.third_party_login_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer thirdPartyLoginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.third_party_login_token
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String thirdPartyLoginToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.invite_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.sign_consistent_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer signConsistentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.sign_total_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer signTotalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.accumulated_score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Long accumulatedScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.sign_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date signTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.real_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.hometown
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String hometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.last_login_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.current_residence
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String currentResidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.constellation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.has_bangbi_bean_account
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer hasBangbiBeanAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.user_mps
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String userMps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.status
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.is_cart_notice
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Integer isCartNotice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.updated_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.is_real_identity
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private Boolean isRealIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_center.remarks
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.user_id
     *
     * @return the value of t_user_center.user_id
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.user_id
     *
     * @param userId the value for t_user_center.user_id
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.mobile
     *
     * @return the value of t_user_center.mobile
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.mobile
     *
     * @param mobile the value for t_user_center.mobile
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.is_mobile_bind
     *
     * @return the value of t_user_center.is_mobile_bind
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getIsMobileBind() {
        return isMobileBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.is_mobile_bind
     *
     * @param isMobileBind the value for t_user_center.is_mobile_bind
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setIsMobileBind(Integer isMobileBind) {
        this.isMobileBind = isMobileBind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.user_name
     *
     * @return the value of t_user_center.user_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.user_name
     *
     * @param userName the value for t_user_center.user_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.password
     *
     * @return the value of t_user_center.password
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.password
     *
     * @param password the value for t_user_center.password
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.email
     *
     * @return the value of t_user_center.email
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.email
     *
     * @param email the value for t_user_center.email
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.birthday
     *
     * @return the value of t_user_center.birthday
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.birthday
     *
     * @param birthday the value for t_user_center.birthday
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.signature
     *
     * @return the value of t_user_center.signature
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.signature
     *
     * @param signature the value for t_user_center.signature
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.gender
     *
     * @return the value of t_user_center.gender
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.gender
     *
     * @param gender the value for t_user_center.gender
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.score
     *
     * @return the value of t_user_center.score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Long getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.score
     *
     * @param score the value for t_user_center.score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setScore(Long score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.city
     *
     * @return the value of t_user_center.city
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.city
     *
     * @param city the value for t_user_center.city
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.nick_name
     *
     * @return the value of t_user_center.nick_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.nick_name
     *
     * @param nickName the value for t_user_center.nick_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.avatar
     *
     * @return the value of t_user_center.avatar
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.avatar
     *
     * @param avatar the value for t_user_center.avatar
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.active_code
     *
     * @return the value of t_user_center.active_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.active_code
     *
     * @param activeCode the value for t_user_center.active_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.activation
     *
     * @return the value of t_user_center.activation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getActivation() {
        return activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.activation
     *
     * @param activation the value for t_user_center.activation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setActivation(String activation) {
        this.activation = activation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.create_time
     *
     * @return the value of t_user_center.create_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.create_time
     *
     * @param createTime the value for t_user_center.create_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.update_time
     *
     * @return the value of t_user_center.update_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.update_time
     *
     * @param updateTime the value for t_user_center.update_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.find_pw_code
     *
     * @return the value of t_user_center.find_pw_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getFindPwCode() {
        return findPwCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.find_pw_code
     *
     * @param findPwCode the value for t_user_center.find_pw_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setFindPwCode(String findPwCode) {
        this.findPwCode = findPwCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.user_type
     *
     * @return the value of t_user_center.user_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.user_type
     *
     * @param userType the value for t_user_center.user_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.security_level
     *
     * @return the value of t_user_center.security_level
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.security_level
     *
     * @param securityLevel the value for t_user_center.security_level
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setSecurityLevel(Integer securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.third_party_login_type
     *
     * @return the value of t_user_center.third_party_login_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getThirdPartyLoginType() {
        return thirdPartyLoginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.third_party_login_type
     *
     * @param thirdPartyLoginType the value for t_user_center.third_party_login_type
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setThirdPartyLoginType(Integer thirdPartyLoginType) {
        this.thirdPartyLoginType = thirdPartyLoginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.third_party_login_token
     *
     * @return the value of t_user_center.third_party_login_token
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getThirdPartyLoginToken() {
        return thirdPartyLoginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.third_party_login_token
     *
     * @param thirdPartyLoginToken the value for t_user_center.third_party_login_token
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setThirdPartyLoginToken(String thirdPartyLoginToken) {
        this.thirdPartyLoginToken = thirdPartyLoginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.invite_code
     *
     * @return the value of t_user_center.invite_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.invite_code
     *
     * @param inviteCode the value for t_user_center.invite_code
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.sign_consistent_count
     *
     * @return the value of t_user_center.sign_consistent_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getSignConsistentCount() {
        return signConsistentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.sign_consistent_count
     *
     * @param signConsistentCount the value for t_user_center.sign_consistent_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setSignConsistentCount(Integer signConsistentCount) {
        this.signConsistentCount = signConsistentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.sign_total_count
     *
     * @return the value of t_user_center.sign_total_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getSignTotalCount() {
        return signTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.sign_total_count
     *
     * @param signTotalCount the value for t_user_center.sign_total_count
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setSignTotalCount(Integer signTotalCount) {
        this.signTotalCount = signTotalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.accumulated_score
     *
     * @return the value of t_user_center.accumulated_score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Long getAccumulatedScore() {
        return accumulatedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.accumulated_score
     *
     * @param accumulatedScore the value for t_user_center.accumulated_score
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setAccumulatedScore(Long accumulatedScore) {
        this.accumulatedScore = accumulatedScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.sign_time
     *
     * @return the value of t_user_center.sign_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.sign_time
     *
     * @param signTime the value for t_user_center.sign_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.real_name
     *
     * @return the value of t_user_center.real_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.real_name
     *
     * @param realName the value for t_user_center.real_name
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.hometown
     *
     * @return the value of t_user_center.hometown
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.hometown
     *
     * @param hometown the value for t_user_center.hometown
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.last_login_time
     *
     * @return the value of t_user_center.last_login_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.last_login_time
     *
     * @param lastLoginTime the value for t_user_center.last_login_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.current_residence
     *
     * @return the value of t_user_center.current_residence
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getCurrentResidence() {
        return currentResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.current_residence
     *
     * @param currentResidence the value for t_user_center.current_residence
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setCurrentResidence(String currentResidence) {
        this.currentResidence = currentResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.constellation
     *
     * @return the value of t_user_center.constellation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.constellation
     *
     * @param constellation the value for t_user_center.constellation
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.has_bangbi_bean_account
     *
     * @return the value of t_user_center.has_bangbi_bean_account
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getHasBangbiBeanAccount() {
        return hasBangbiBeanAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.has_bangbi_bean_account
     *
     * @param hasBangbiBeanAccount the value for t_user_center.has_bangbi_bean_account
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setHasBangbiBeanAccount(Integer hasBangbiBeanAccount) {
        this.hasBangbiBeanAccount = hasBangbiBeanAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.user_mps
     *
     * @return the value of t_user_center.user_mps
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getUserMps() {
        return userMps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.user_mps
     *
     * @param userMps the value for t_user_center.user_mps
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUserMps(String userMps) {
        this.userMps = userMps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.status
     *
     * @return the value of t_user_center.status
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.status
     *
     * @param status the value for t_user_center.status
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.is_cart_notice
     *
     * @return the value of t_user_center.is_cart_notice
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Integer getIsCartNotice() {
        return isCartNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.is_cart_notice
     *
     * @param isCartNotice the value for t_user_center.is_cart_notice
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setIsCartNotice(Integer isCartNotice) {
        this.isCartNotice = isCartNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.updated_time
     *
     * @return the value of t_user_center.updated_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.updated_time
     *
     * @param updatedTime the value for t_user_center.updated_time
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.is_real_identity
     *
     * @return the value of t_user_center.is_real_identity
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public Boolean getIsRealIdentity() {
        return isRealIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.is_real_identity
     *
     * @param isRealIdentity the value for t_user_center.is_real_identity
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setIsRealIdentity(Boolean isRealIdentity) {
        this.isRealIdentity = isRealIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_center.remarks
     *
     * @return the value of t_user_center.remarks
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_center.remarks
     *
     * @param remarks the value for t_user_center.remarks
     *
     * @mbggenerated Thu Jan 28 14:03:00 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}