package com.xiaya.ucenter.model;

import java.util.Date;

public class UserBistats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.id
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.bistat
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private String bistat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.bizinfo
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private String bizinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.create_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.update_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_bistats.remarks
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.id
     *
     * @return the value of t_user_bistats.id
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.id
     *
     * @param id the value for t_user_bistats.id
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.bistat
     *
     * @return the value of t_user_bistats.bistat
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public String getBistat() {
        return bistat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.bistat
     *
     * @param bistat the value for t_user_bistats.bistat
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setBistat(String bistat) {
        this.bistat = bistat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.bizinfo
     *
     * @return the value of t_user_bistats.bizinfo
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public String getBizinfo() {
        return bizinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.bizinfo
     *
     * @param bizinfo the value for t_user_bistats.bizinfo
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setBizinfo(String bizinfo) {
        this.bizinfo = bizinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.create_time
     *
     * @return the value of t_user_bistats.create_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.create_time
     *
     * @param createTime the value for t_user_bistats.create_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.update_time
     *
     * @return the value of t_user_bistats.update_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.update_time
     *
     * @param updateTime the value for t_user_bistats.update_time
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_bistats.remarks
     *
     * @return the value of t_user_bistats.remarks
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_bistats.remarks
     *
     * @param remarks the value for t_user_bistats.remarks
     *
     * @mbggenerated Tue Mar 08 17:50:03 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}